name: travel_talk
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/images.jpg
    - assets/images/aaaa.jpg
    - assets/images/pyramids.jpg
    - assets/images/aa.webp

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
