// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMJ9Sv60J2iuElQfAMdanHMTSFMAfnXY8',
    appId: '1:629133287444:web:a5232f9affb78d25efc701',
    messagingSenderId: '629133287444',
    projectId: 'travel-talk-48167',
    authDomain: 'travel-talk-48167.firebaseapp.com',
    storageBucket: 'travel-talk-48167.firebasestorage.app',
    measurementId: 'G-9GRK6NHTMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByTsmDQxAcOgYIV7y3KeSBLgbovtIbrts',
    appId: '1:629133287444:android:79a72ef75f171ecbefc701',
    messagingSenderId: '629133287444',
    projectId: 'travel-talk-48167',
    storageBucket: 'travel-talk-48167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNzx0PIixUDX7vjfPl8A6vvWIR6TRK0-o',
    appId: '1:629133287444:ios:db74cd973bc37641efc701',
    messagingSenderId: '629133287444',
    projectId: 'travel-talk-48167',
    storageBucket: 'travel-talk-48167.firebasestorage.app',
    iosBundleId: 'com.example.travelTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNzx0PIixUDX7vjfPl8A6vvWIR6TRK0-o',
    appId: '1:629133287444:ios:db74cd973bc37641efc701',
    messagingSenderId: '629133287444',
    projectId: 'travel-talk-48167',
    storageBucket: 'travel-talk-48167.firebasestorage.app',
    iosBundleId: 'com.example.travelTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMJ9Sv60J2iuElQfAMdanHMTSFMAfnXY8',
    appId: '1:629133287444:web:4af0fc21417473ccefc701',
    messagingSenderId: '629133287444',
    projectId: 'travel-talk-48167',
    authDomain: 'travel-talk-48167.firebaseapp.com',
    storageBucket: 'travel-talk-48167.firebasestorage.app',
    measurementId: 'G-RL3BTNL867',
  );
}
